name: Node CI

on:
  schedule:
    - cron: "30 12 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build
          npm run deploy
        env:
          CI: true
          REPO_NAME: auto-commit
          REPO_HOST: github.com
          REPO_USER: Marhc
          REPO_BRANCH: master
          USER_NAME: marhc
          USER_EMAIL: ${{ secrets.USER_EMAIL }}
          USER_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEBUG: simple-git
